import { Sector } from "./types";

export const SECTORS: Sector[] = [
  {
    id: "corruption",
    name: "Corruption & Transparency",
    icon: "Scale",
    description:
      "Public sector corruption, bribery, and lack of institutional transparency",
    indiaRank: 93,
    globalAverage: 45,
    leaderCountry: "Denmark",
    leaderScore: 90,
    gapPercent: 48,
    keyIssues: [
      "Bureaucratic red tape enabling bribery",
      "Political funding opacity",
      "Weak whistleblower protection",
      "Delayed judicial prosecution of corrupt officials",
      "Lack of real-time public expenditure tracking",
    ],
    trend: "stable",
  },
  {
    id: "education",
    name: "Education Quality",
    icon: "GraduationCap",
    description:
      "Learning outcomes, teacher quality, and access to quality education",
    indiaRank: 132,
    globalAverage: 65,
    leaderCountry: "Finland",
    leaderScore: 95,
    gapPercent: 63,
    keyIssues: [
      "Low PISA scores and learning poverty",
      "Teacher absenteeism in rural schools",
      "Outdated curriculum lacking critical thinking",
      "Digital divide in online education",
      "Rote learning over skill development",
    ],
    trend: "improving",
  },
  {
    id: "healthcare",
    name: "Healthcare Access",
    icon: "Heart",
    description:
      "Universal healthcare coverage, doctor-patient ratio, and public health",
    indiaRank: 66,
    globalAverage: 50,
    leaderCountry: "Japan",
    leaderScore: 92,
    gapPercent: 26,
    keyIssues: [
      "1:1458 doctor-patient ratio vs WHO norm of 1:1000",
      "70% out-of-pocket healthcare spending",
      "Rural healthcare infrastructure gaps",
      "High infant and maternal mortality in states",
      "Insufficient public health spending (1.3% GDP)",
    ],
    trend: "improving",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    icon: "Building2",
    description:
      "Roads, railways, urban planning, water, and sanitation infrastructure",
    indiaRank: 51,
    globalAverage: 40,
    leaderCountry: "Singapore",
    leaderScore: 96,
    gapPercent: 45,
    keyIssues: [
      "Urban congestion and poor public transit",
      "Water scarcity in 21 major cities by 2030",
      "Rural road connectivity gaps",
      "Delayed infrastructure project completion",
      "Inadequate waste management systems",
    ],
    trend: "improving",
  },
  {
    id: "economy",
    name: "Economic Competitiveness",
    icon: "TrendingUp",
    description:
      "Ease of doing business, employment, and economic inequality",
    indiaRank: 63,
    globalAverage: 45,
    leaderCountry: "Singapore",
    leaderScore: 88,
    gapPercent: 25,
    keyIssues: [
      "Youth unemployment at 23%",
      "Informal sector dominance (90% workforce)",
      "Wealth inequality (Gini: 0.35)",
      "Complex tax and regulatory compliance",
      "Low manufacturing share of GDP",
    ],
    trend: "improving",
  },
  {
    id: "governance",
    name: "Governance & Bureaucracy",
    icon: "Landmark",
    description:
      "Administrative efficiency, e-governance, and policy implementation",
    indiaRank: 77,
    globalAverage: 50,
    leaderCountry: "Estonia",
    leaderScore: 91,
    gapPercent: 14,
    keyIssues: [
      "Slow policy implementation cycles",
      "Inter-departmental coordination failures",
      "Paper-based processes in many states",
      "Civil service accountability gaps",
      "Fragmented digital government systems",
    ],
    trend: "improving",
  },
  {
    id: "environment",
    name: "Environment & Climate",
    icon: "Leaf",
    description:
      "Air quality, climate action, renewable energy, and sustainability",
    indiaRank: 176,
    globalAverage: 80,
    leaderCountry: "Sweden",
    leaderScore: 94,
    gapPercent: 82,
    keyIssues: [
      "22 of 30 most polluted cities globally are in India",
      "Coal dependency (70% energy mix)",
      "Rapid deforestation and biodiversity loss",
      "Water body contamination",
      "Weak enforcement of environmental laws",
    ],
    trend: "declining",
  },
  {
    id: "technology",
    name: "Technology & Innovation",
    icon: "Cpu",
    description:
      "R&D investment, startup ecosystem, and digital infrastructure",
    indiaRank: 40,
    globalAverage: 35,
    leaderCountry: "USA",
    leaderScore: 95,
    gapPercent: 55,
    keyIssues: [
      "R&D spending only 0.7% of GDP vs 3% in developed nations",
      "Brain drain of top tech talent",
      "Low patent filings per capita",
      "Digital literacy gaps in rural areas",
      "Dependence on imported semiconductors",
    ],
    trend: "improving",
  },
  {
    id: "agriculture",
    name: "Agriculture & Food Security",
    icon: "Wheat",
    description:
      "Farmer income, agricultural productivity, and food supply chain",
    indiaRank: 68,
    globalAverage: 55,
    leaderCountry: "Netherlands",
    leaderScore: 90,
    gapPercent: 22,
    keyIssues: [
      "Farmer distress and suicide rates",
      "Middlemen exploitation in supply chains",
      "Climate vulnerability of crops",
      "Low agricultural mechanization",
      "Inadequate crop insurance penetration",
    ],
    trend: "stable",
  },
  {
    id: "judiciary",
    name: "Judicial System",
    icon: "Gavel",
    description:
      "Speed of justice, case backlog, and legal accessibility",
    indiaRank: 79,
    globalAverage: 50,
    leaderCountry: "Singapore",
    leaderScore: 88,
    gapPercent: 9,
    keyIssues: [
      "4.7 crore pending court cases",
      "Average case resolution: 10+ years",
      "Limited legal aid for poor citizens",
      "Overburdened judiciary (19 judges per million)",
      "Low conviction rates in corruption cases",
    ],
    trend: "stable",
  },
  {
    id: "women-safety",
    name: "Women Safety & Equality",
    icon: "Shield",
    description:
      "Gender equality index, safety, workforce participation",
    indiaRank: 129,
    globalAverage: 70,
    leaderCountry: "Iceland",
    leaderScore: 91,
    gapPercent: 62,
    keyIssues: [
      "Low female labor force participation (24%)",
      "High rates of gender-based violence",
      "Wage gap and workplace discrimination",
      "Poor street safety in urban areas",
      "Inadequate representation in leadership roles",
    ],
    trend: "improving",
  },
  {
    id: "poverty",
    name: "Poverty & Inequality",
    icon: "Users",
    description:
      "Multidimensional poverty, social mobility, and welfare delivery",
    indiaRank: 62,
    globalAverage: 40,
    leaderCountry: "Norway",
    leaderScore: 93,
    gapPercent: 31,
    keyIssues: [
      "230 million still in multidimensional poverty",
      "Leakage in welfare scheme delivery",
      "Inter-generational poverty traps",
      "Regional development disparities",
      "Inadequate social safety nets for gig workers",
    ],
    trend: "improving",
  },
];

export function getSectorById(id: string): Sector | undefined {
  return SECTORS.find((s) => s.id === id);
}